- project:
    check:
      jobs:
        - networking-l2gw-tempest-dummy
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - networking-l2gw-tempest-dummy
        - openstack-tox-lower-constraints
